# Generated by Django 5.1.2 on 2024-11-23 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAppend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('comic', '漫画'), ('anime', 'アニメ'), ('game', 'ゲーム'), ('music', '音楽'), ('sports', 'スポーツ'), ('sonota', 'その他')], max_length=20, verbose_name='趣味')),
                ('append_content1', models.CharField(blank=True, max_length=50, null=True, verbose_name='詳細')),
                ('append_image1', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='ContentAppend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('append_content2', models.CharField(max_length=50, verbose_name='追加詳細')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status_app.categoryappend', verbose_name='趣味')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAppend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('append_image2', models.ImageField(upload_to='photos', verbose_name='追加画像')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status_app.categoryappend', verbose_name='趣味')),
            ],
        ),
    ]
